# 数据库配置
spring:
  application:
    name: smartrmtrade
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL
    username:
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
            acquireTriggersWithinLock: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc

# mybatis配置
mybatis:
  config-location:
    classpath: mybatis/mybatis-config.xml
  mapper-locations:
    classpath*: mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

server:
  port: 10081
  tomcat:
    maxThreads: 200
    maxConnections: 1000
    acceptCount: 100

commodity:
  file:
    json:
      path: commodity_new.json
jwt:
  key: c21hcnRybS1kZGRzbWFydHJtLWRkZHNtYXJ0cm0tZGRk
  expirationSecs: 2592000
logging:
  level:
    com:
      smartrm:
        smartrmtrade:
          trade:
            infrastructure:
              mapper: debug
            application: debug
aliyun:
  accessKey: xxxx
  accessSecret: xxxx
  iot:
    endpoint: iot.cn-shanghai.aliyuncs.com
    consumerGroup: xxxx
    amqp:
      host: 1984706750605697.iot-amqp.cn-shanghai.aliyuncs.com
    instanceId:
wechat:
  pay:
    appId: wx8888888888888888
    mchId: 12888888
    key: 88888888888888888888888888888888
    certPath: /path/to/cert
    notifyUrl: http://smartrm.techcoffee.com/payment/wx/notify
kafka:
  server: localhost:9092
  retries: 3
  batch:
    size: 16384
  linger:
    ms: 1
  buffer:
    memory: 33554432
remote:
  baseUri:
    pay: http://pay/pay
    device: http://device/mock/device
    user: http://user/user
    commodity: http://commodity/commodity
  connectTimeout: 2000
  readTimeout: 5000
opentracing:
  zipkin:
    enabled: true
    http-sender:
      baseUrl: http://zipkin:9411/
rocketmq:
  nameServer: 47.97.27.57:9876
mq:
  server: 47.97.27.57:9876

